import px
from neopixel import *
strip = Adafruit_NeoPixel(50, 18, 800000, 5, False, 255, 0, ws.WS2811_STRIP_RGB)
strip.begin()
px.solid(strip, px.BLACK)
while(True):
   px.load_rainbow_cycle(strip)
   px.fade_in(strip, 3)
   px.rainbow_cycle(strip, wait_ms=20, iterations=1)
   px.fade_out(strip, 3)
   px.solid(strip, px.BLACK)
   strip.setBrightness(255)
   px.load_random_colors()
   px.colors_up(strip, 60)
   px.colors_down(strip, 60)
   px.colors(strip)
   px.random_flash(strip, 20)
   px.alternate(strip, px.RED, px.GREEN, 100)
   px.random_flash(strip, 20)
   px.unalternate(strip, 100)
   px.from_middle(strip, px.AQUA, 100)
   px.from_middle(strip, px.RED, 100)
   px.from_middle(strip, px.GREEN, 100)
   px.alternate(strip, px.BLUE, px.WARM_WHITE, 100)
   px.random_flash(strip, 20)
   px.fade_out(strip, 3)
   px.colors(strip)
   px.fade_in(strip, 3)
   px.random_flash(strip, 20)
   px.fade_out(strip, 3)
